server:
  port: 5001
spring:
  application:
    name: EKART_GATEWAY
  cloud:
    gateway:
      routes:
      - id: order-service
        uri: lb://ORDER_SERVICE
        predicates:
        - Path= /order/**
      - id: payment-service
        uri: lb://PAYMENT_SERVICE
        predicates:
        - Path= /payment/**
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5000/eureka
  instance:
    hostname: localhost