server:
  port: 5004
spring:
  application:
    name: PAYMENT_SERVICE
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:itachi
    #platform: postgresql
    #url: jdbc:postgresql://localhost:3001/itachi  #can spcify login credentials here, lives at http://localhost:5004/h2-console
    #username: itachi
    #password: itachi
    
#eureka config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5000/eureka
    
#slf4j config
logging:
  level:
    com.itachi.ekart: DEBUG
  pattern:
    console: "[%-5p] [%d{dd HH:mm:ss}] [%F#%L] [%3C-%M] -%m%n"  #p priority, d{} date{formate}, F filename, L lineNo, C FullClass, M method, m msg, n newline
    file: "[%-5p] [%d{dd HH:mm:ss}] [%F#%L] [%3C-%M] -%m%n"
    